AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DeleteEc2Instances:
      Type: AWS::Serverless::Function
      Properties:
        Handler: ec2-terminator.handler
        CodeUri: ./lambda
        Runtime: python3.7
        Policies:
          - Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource: arn:aws:logs:*:*:*
