on:
  push:
    branches:
      - feature_*

name: Check AWS Cloudformation template

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key }}
        aws-secret-access-key: ${{ secrets.aws_secret_key }}
        aws-region: eu-central-1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        aws cloudformation validate-template --template-body ./terminate-ec2-instances/template.yaml
        # aws cloudformation deploy --template-file ./terminate-ec2-instances/template.yaml --capabilities CAPABILITY_NAMED_IAM --stack-name my-new-stack
        # aws cloudformation deploy --template-file /path_t
